### PR TITLE
Scoreboard page

### PR DESCRIPTION
**Pull request by TirananE**
- Show the first max score and their user login (email) and their score.
- Add button back to main menu

### CODE REVIEW

**Comment by KasidisGit** [comment]
I think we should add more information of the player. 👾

**Comment by KasidisGit** [comment]
I added a player image, please give feedback. :octocat:

**Comment by noeybynk** [comment]
I think it's good. but you should adjust the size of profile picture to fit in the table and decorate wallpaper picture
- when scroll to bottom, background does not cover all of page.

**Comment by SukritaEarn** [comment]
Everything looks perfect right now. 👍

**Comment by SukritaEarn** [comment]
Everything looks perfect right now. 👍

**Pull request merged**
